# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    vlmOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *manf
                    - *rta
                    - *dlr
                    - *scr
                    - *bank
                    - *insu
                    - *traf

    vlmOrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *manf
                    - *rta
                    - *dlr
                    - *scr
                    - *bank
                    - *insu
                    - *traf

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/vlm.com/msp

    - &manf 
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: manfMSP

        # ID to load the MSP definition as
        ID: manfMSP

        MSPDir: crypto-config/peerOrganizations/manf.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.manf.vlm.com
              Port: 7051
    - &rta 
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: rtaMSP

        # ID to load the MSP definition as
        ID: rtaMSP

        MSPDir: crypto-config/peerOrganizations/rta.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.rta.vlm.com
              Port: 7051
    - &dlr 
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: dlrMSP

        # ID to load the MSP definition as
        ID: dlrMSP

        MSPDir: crypto-config/peerOrganizations/dlr.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.dlr.vlm.com
              Port: 7051

    - &scr 
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: scrMSP

        # ID to load the MSP definition as
        ID: scrMSP

        MSPDir: crypto-config/peerOrganizations/scr.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.scr.vlm.com
              Port: 7051

    - &bank
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: bankMSP

        # ID to load the MSP definition as
        ID: bankMSP

        MSPDir: crypto-config/peerOrganizations/bank.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.bank.vlm.com
              Port: 7051

    - &insu
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: insuMSP

        # ID to load the MSP definition as
        ID: insuMSP

        MSPDir: crypto-config/peerOrganizations/insu.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.insu.vlm.com
              Port: 7051

    - &traf
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: trafMSP

        # ID to load the MSP definition as
        ID: trafMSP

        MSPDir: crypto-config/peerOrganizations/traf.vlm.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.traf.vlm.com
              Port: 7051
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.vlm.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
